# This is a basic workflow to help you get started with Actions

name: User Metrics

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Metrics Embed
        uses: lowlighter/metrics@v3.34
        with:
            token: ${{secrets.METRICS_TOKEN}}
            template: classic
            base: header, repositories, activity, community, metadata
            base_indepth: yes
            plugin_lines: yes
            plugin_languages: yes
            plugin_languages_indepth: yes
            plugin_habits: yes
            plugin_isocalendar: yes
            plugin_introduction: yes
            # plugin_achievements: yes











  
          
